"""add_personal_email_and_gender_to_employees

Revision ID: 100f1a014ed3
Revises: 41a42e8c59ea
Create Date: 2026-09-06 02:25:26.089861

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '100f1a014ed3'
down_revision: Union[str, Sequence[str], None] = '41a42e8c59ea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('fk_contract_salary_structure', 'contracts', 'salary_structures', ['salary_structure_id'], ['id'], use_alter=True)
    op.create_foreign_key('fk_dept_manager', 'departments', 'employees', ['manager_id'], ['id'], use_alter=True)
    op.add_column('employees', sa.Column('personal_email', sa.String(length=255), nullable=True))
    op.add_column('employees', sa.Column('gender', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('employees', 'gender')
    op.drop_column('employees', 'personal_email')
    op.drop_constraint('fk_dept_manager', 'departments', type_='foreignkey')
    op.drop_constraint('fk_contract_salary_structure', 'contracts', type_='foreignkey')
    # ### end Alembic commands ###
