"""full_schema

Revision ID: 41a42e8c59ea
Revises: 88239dba9d16
Create Date: 2026-09-05 12:00:39.796653

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '41a42e8c59ea'
down_revision: Union[str, Sequence[str], None] = '88239dba9d16'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('departments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('manager_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['manager_id'], ['employees.id'], name='fk_dept_manager', use_alter=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_departments_id'), 'departments', ['id'], unique=False)
    op.create_table('salary_structures',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_salary_structures_id'), 'salary_structures', ['id'], unique=False)
    op.create_table('time_off_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('unit', sa.String(length=20), nullable=False),
    sa.Column('requires_allocation', sa.Boolean(), nullable=False),
    sa.Column('approval', sa.String(length=20), nullable=False),
    sa.Column('display_color', sa.String(length=30), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_time_off_types_id'), 'time_off_types', ['id'], unique=False)
    op.create_table('working_schedules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('company', sa.String(length=255), nullable=False),
    sa.Column('days_per_week', sa.Integer(), nullable=False),
    sa.Column('hours_per_week', sa.Float(), nullable=False),
    sa.Column('timezone', sa.String(length=100), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_working_schedules_id'), 'working_schedules', ['id'], unique=False)
    op.create_table('employees',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('job_position', sa.String(length=255), nullable=True),
    sa.Column('department_id', sa.Integer(), nullable=True),
    sa.Column('manager_id', sa.Integer(), nullable=True),
    sa.Column('work_location', sa.String(length=255), nullable=True),
    sa.Column('work_email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('company', sa.String(length=255), nullable=False),
    sa.Column('working_schedule_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('private_address', sa.String(length=512), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.ForeignKeyConstraint(['manager_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['working_schedule_id'], ['working_schedules.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_employees_department_id'), 'employees', ['department_id'], unique=False)
    op.create_index(op.f('ix_employees_id'), 'employees', ['id'], unique=False)
    op.create_index(op.f('ix_employees_name'), 'employees', ['name'], unique=False)
    op.create_index(op.f('ix_employees_user_id'), 'employees', ['user_id'], unique=True)
    op.create_index(op.f('ix_employees_work_email'), 'employees', ['work_email'], unique=True)
    op.create_table('payruns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('salary_structure_id', sa.Integer(), nullable=False),
    sa.Column('date_from', sa.Date(), nullable=False),
    sa.Column('date_to', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['salary_structure_id'], ['salary_structures.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payruns_id'), 'payruns', ['id'], unique=False)
    op.create_table('salary_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('salary_structure_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('computation', sa.String(length=20), nullable=False),
    sa.Column('fixed_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('percentage', sa.Float(), nullable=True),
    sa.Column('percentage_base', sa.String(length=50), nullable=True),
    sa.Column('python_code', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['salary_structure_id'], ['salary_structures.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_salary_rules_id'), 'salary_rules', ['id'], unique=False)
    op.create_index(op.f('ix_salary_rules_salary_structure_id'), 'salary_rules', ['salary_structure_id'], unique=False)
    op.create_table('schedule_lines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('schedule_id', sa.Integer(), nullable=False),
    sa.Column('day_of_week', sa.String(length=10), nullable=False),
    sa.Column('start_time', sa.String(length=10), nullable=False),
    sa.Column('end_time', sa.String(length=10), nullable=False),
    sa.Column('break_hours', sa.Float(), nullable=False),
    sa.Column('work_hours', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['schedule_id'], ['working_schedules.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_schedule_lines_id'), 'schedule_lines', ['id'], unique=False)
    op.create_index(op.f('ix_schedule_lines_schedule_id'), 'schedule_lines', ['schedule_id'], unique=False)
    op.create_table('attendance_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('check_in', sa.DateTime(timezone=True), nullable=True),
    sa.Column('check_out', sa.DateTime(timezone=True), nullable=True),
    sa.Column('worked_hours', sa.Float(), nullable=False),
    sa.Column('overtime_hours', sa.Float(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_attendance_records_employee_id'), 'attendance_records', ['employee_id'], unique=False)
    op.create_index(op.f('ix_attendance_records_id'), 'attendance_records', ['id'], unique=False)
    op.create_table('contracts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reference', sa.String(length=50), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=True),
    sa.Column('job_position', sa.String(length=255), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('wage_monthly', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('working_schedule_id', sa.Integer(), nullable=True),
    sa.Column('salary_structure_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['salary_structure_id'], ['salary_structures.id'], name='fk_contract_salary_structure', use_alter=True),
    sa.ForeignKeyConstraint(['working_schedule_id'], ['working_schedules.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contracts_employee_id'), 'contracts', ['employee_id'], unique=False)
    op.create_index(op.f('ix_contracts_id'), 'contracts', ['id'], unique=False)
    op.create_index(op.f('ix_contracts_reference'), 'contracts', ['reference'], unique=True)
    op.create_table('time_off_allocations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('time_off_type_id', sa.Integer(), nullable=False),
    sa.Column('allocated_days', sa.Float(), nullable=False),
    sa.Column('taken_days', sa.Float(), nullable=False),
    sa.Column('approver_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('validity_label', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['approver_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['time_off_type_id'], ['time_off_types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_time_off_allocations_employee_id'), 'time_off_allocations', ['employee_id'], unique=False)
    op.create_index(op.f('ix_time_off_allocations_id'), 'time_off_allocations', ['id'], unique=False)
    op.create_index(op.f('ix_time_off_allocations_time_off_type_id'), 'time_off_allocations', ['time_off_type_id'], unique=False)
    op.create_table('payslips',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('payrun_id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('salary_structure_id', sa.Integer(), nullable=False),
    sa.Column('contract_id', sa.Integer(), nullable=True),
    sa.Column('date_from', sa.Date(), nullable=False),
    sa.Column('date_to', sa.Date(), nullable=False),
    sa.Column('worked_days', sa.Integer(), nullable=False),
    sa.Column('basic_wage', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('gross_wage', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('net_wage', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('has_warning', sa.Boolean(), nullable=False),
    sa.Column('warning_message', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['contract_id'], ['contracts.id'], ),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['payrun_id'], ['payruns.id'], ),
    sa.ForeignKeyConstraint(['salary_structure_id'], ['salary_structures.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payslips_employee_id'), 'payslips', ['employee_id'], unique=False)
    op.create_index(op.f('ix_payslips_id'), 'payslips', ['id'], unique=False)
    op.create_index(op.f('ix_payslips_payrun_id'), 'payslips', ['payrun_id'], unique=False)
    op.create_table('time_off_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('time_off_type_id', sa.Integer(), nullable=False),
    sa.Column('allocation_id', sa.Integer(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('duration_days', sa.Float(), nullable=False),
    sa.Column('approver_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['allocation_id'], ['time_off_allocations.id'], ),
    sa.ForeignKeyConstraint(['approver_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['time_off_type_id'], ['time_off_types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_time_off_requests_employee_id'), 'time_off_requests', ['employee_id'], unique=False)
    op.create_index(op.f('ix_time_off_requests_id'), 'time_off_requests', ['id'], unique=False)
    op.create_index(op.f('ix_time_off_requests_time_off_type_id'), 'time_off_requests', ['time_off_type_id'], unique=False)
    op.create_table('payslip_lines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('payslip_id', sa.Integer(), nullable=False),
    sa.Column('rule_name', sa.String(length=255), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['payslip_id'], ['payslips.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payslip_lines_id'), 'payslip_lines', ['id'], unique=False)
    op.create_index(op.f('ix_payslip_lines_payslip_id'), 'payslip_lines', ['payslip_id'], unique=False)
    op.add_column('users', sa.Column('role', sa.String(length=50), server_default='employee', nullable=False))
    op.add_column('users', sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_active')
    op.drop_column('users', 'role')
    op.drop_index(op.f('ix_payslip_lines_payslip_id'), table_name='payslip_lines')
    op.drop_index(op.f('ix_payslip_lines_id'), table_name='payslip_lines')
    op.drop_table('payslip_lines')
    op.drop_index(op.f('ix_time_off_requests_time_off_type_id'), table_name='time_off_requests')
    op.drop_index(op.f('ix_time_off_requests_id'), table_name='time_off_requests')
    op.drop_index(op.f('ix_time_off_requests_employee_id'), table_name='time_off_requests')
    op.drop_table('time_off_requests')
    op.drop_index(op.f('ix_payslips_payrun_id'), table_name='payslips')
    op.drop_index(op.f('ix_payslips_id'), table_name='payslips')
    op.drop_index(op.f('ix_payslips_employee_id'), table_name='payslips')
    op.drop_table('payslips')
    op.drop_index(op.f('ix_time_off_allocations_time_off_type_id'), table_name='time_off_allocations')
    op.drop_index(op.f('ix_time_off_allocations_id'), table_name='time_off_allocations')
    op.drop_index(op.f('ix_time_off_allocations_employee_id'), table_name='time_off_allocations')
    op.drop_table('time_off_allocations')
    op.drop_index(op.f('ix_contracts_reference'), table_name='contracts')
    op.drop_index(op.f('ix_contracts_id'), table_name='contracts')
    op.drop_index(op.f('ix_contracts_employee_id'), table_name='contracts')
    op.drop_table('contracts')
    op.drop_index(op.f('ix_attendance_records_id'), table_name='attendance_records')
    op.drop_index(op.f('ix_attendance_records_employee_id'), table_name='attendance_records')
    op.drop_table('attendance_records')
    op.drop_index(op.f('ix_schedule_lines_schedule_id'), table_name='schedule_lines')
    op.drop_index(op.f('ix_schedule_lines_id'), table_name='schedule_lines')
    op.drop_table('schedule_lines')
    op.drop_index(op.f('ix_salary_rules_salary_structure_id'), table_name='salary_rules')
    op.drop_index(op.f('ix_salary_rules_id'), table_name='salary_rules')
    op.drop_table('salary_rules')
    op.drop_index(op.f('ix_payruns_id'), table_name='payruns')
    op.drop_table('payruns')
    op.drop_index(op.f('ix_employees_work_email'), table_name='employees')
    op.drop_index(op.f('ix_employees_user_id'), table_name='employees')
    op.drop_index(op.f('ix_employees_name'), table_name='employees')
    op.drop_index(op.f('ix_employees_id'), table_name='employees')
    op.drop_index(op.f('ix_employees_department_id'), table_name='employees')
    op.drop_table('employees')
    op.drop_index(op.f('ix_working_schedules_id'), table_name='working_schedules')
    op.drop_table('working_schedules')
    op.drop_index(op.f('ix_time_off_types_id'), table_name='time_off_types')
    op.drop_table('time_off_types')
    op.drop_index(op.f('ix_salary_structures_id'), table_name='salary_structures')
    op.drop_table('salary_structures')
    op.drop_index(op.f('ix_departments_id'), table_name='departments')
    op.drop_table('departments')
    # ### end Alembic commands ###
