"""remove_wage_monthly_from_contracts

Revision ID: b3776c18bad7
Revises: 100f1a014ed3
Create Date: 2026-09-06 07:48:14.566513

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b3776c18bad7'
down_revision: Union[str, Sequence[str], None] = '100f1a014ed3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_check_constraint('check_contract_dates', 'contracts', 'end_date IS NULL OR end_date > start_date')
    op.create_unique_constraint('uq_payrun_employee', 'payslips', ['payrun_id', 'employee_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_payrun_employee', 'payslips', type_='unique')
    op.drop_constraint('check_contract_dates', 'contracts', type_='check')
    # ### end Alembic commands ###
